#!/bin/bash
#SBATCH --time=02:00:00
#SBATCH --nodes=1
#SBATCH --gpus=1
#SBATCH --constraint=gpu
#SBATCH --account=m1727_g
#SBATCH --job-name=kestrel
#SBATCH -c 64
#SBATCH -q regular
#SBATCH --output=NOMINAL.LOG

conda init
conda activate SBI
cd /global/cfs/cdirs/lsst/www/DESC_TD_PUBLIC/users/bastienc/kestrel

pip install -e . --quiet

python scripts/run_sims.py --CONFIG "config_files/KESTREL.yml" --SIMULATE
python scripts/run_sims.py --CONFIG "config_files/KESTREL.yml" --TRAIN
